lchrusciel/ApiTestCase

README.md, phpunit.xml, src/ApiTestCase.php, src/JsonApiTestCase.php, src/XmlApiTestCase.php, test/src/Tests/Controller/SampleControllerJsonTest.php, test/src/Tests/Controller/SampleControllerXmlTest.php
=> Directly defining kernel class option

src/ApiTestCase.php, test/src/Tests/Controller/SampleControllerJsonTest.php, test/src/Tests/Controller/SampleControllerXmlTest.php
I think decouple loading methods will be better approach.
=> Refactor loading fixtures by using symfony finder

src/ApiTestCase.php, test/app/config/routing.yml, test/src/Controller/SampleController.php, test/src/Tests/Controller/SampleControllerJsonTest.php, test/src/Tests/Controller/SampleControllerXmlTest.php, test/src/Tests/Responses/Expected/get_product.json, test/src/Tests/Responses/Expected/get_product.xml
Hi,
I'd like to return the objects from the fixture load.
I've added tests to demo my use case.
Cheers!
=> return objects from fixtures

src/ApiTestCase.php
=> [Bug Fix] Re-use the alice fixture loader when loading fixtures

README.md, src/ApiTestCase.php
The only option if your kernel of choice is not in a global namespace and you use an autoloader to load it. More info in readme.
=> Ability to load kernel by class

src/ApiTestCase.php
Hey,
I need to use Processors for some of my objects in my fixtures.
https://github.com/nelmio/alice/blob/2.x/doc/processors.md
This was not possible because the Alice `Loader` was being used, which you can't add processors to.
So i've switched to use the `Fixtures` class.
Thanks
=> use Alice Fixtures instead of Loader, so we can use Processors

src/ApiTestCase.php
@lchrusciel sorry, bug in previous PR.
=> fix Fixtures constructor

src/ApiTestCase.php
Small semantic changes.
Based on #43.
=> Small code clean ups

src/ApiTestCase.php
Warning extraction from #43. 
BC break inside.
=> Prevent fatal error if doctrine is require but not available

test/app/config/routing.yml, test/src/Controller/SampleController.php, test/src/Tests/Controller/SampleControllerJsonTest.php, test/src/Tests/Responses/Expected/create_product.json
It would be great to have all methods used in tests (also PUT, PATCH and DELETE) and I think this is a good step forward 😄 🐫
=> Json POST Product test for sample application

composer.json
| Related tickets | fixes #75, fixes #76 
=> Do not lock doctrine/data-fixtures >=1.1 <1.2

src/ApiTestCase.php
| Bug fix?        |yes
| Related tickets | fixes #X, partially #Y, mentioned in #Z
On my project, this reduces the memory usage from 450MB to 100MB, and reduces the run time from 4.5 to 3.3 minutes.
=> Fix memory leaks

src/MediaTypes.php
=> Added JsonLd

.gitattributes, .gitignore, .travis.yml, composer.json, phpunit.xml.dist, test/.gitignore, test/app/AppKernel.php
| BC breaks?      | kind of
| Related tickets | -
=> Bump dependencies for 2.0 release

README.md
| Related tickets | Adds readme for #87 
=> [README] Add TMP_DIR to reference

.travis.yml, README.md, composer.json, phpunit.xml.dist, src/ApiTestCase.php, test/app/AppKernel.php, test/app/console
| New feature?    | yes
| BC breaks?      | yes
| Related tickets | N/A
=> add symfony 4 support

.travis.yml
=> [Travis] Support for php 7.2

composer.json
=> [Composer] Change branch alias

.travis.yml, composer.json
It would be great if this could end up in 3.0, since PHPUnit 7.0 is released in two weeks time :)
| New feature?    | yes
| Related tickets | N/A
=> Allow installation of PHPUnit 7.0

.travis.yml
| Related tickets | https://github.com/Lakion/ApiTestCase/pull/108#issuecomment-363761388
=> [Maintenance] Support PHPUnit 7.0

UPGRADE.md
| Related tickets | fixes #107
=> [UPGRADE] Document parameter name change

UPGRADE.md
=> Update UPGRADE file

src/ApiTestCase.php, test/app/config/doctrine/Category.orm.yml, test/app/config/routing.yml, test/src/Controller/SampleController.php, test/src/Entity/Category.php, test/src/Tests/Controller/SampleControllerJsonTest.php, test/src/Tests/Controller/SampleControllerXmlTest.php, test/src/Tests/DataFixtures/ORM/category.yml, test/src/Tests/Responses/Expected/category_index.json, test/src/Tests/Responses/Expected/category_index.xml
| New feature?    | yes
In current `nelmio/alice` version, if there is a reference to another entity which is not in the same fixture file, these files needs to be loaded together.
=> Load multiple fixtures at once

UPGRADE.md
| Related tickets | fixes https://github.com/Lakion/ApiTestCase/issues/116
=> Update UPGRADE file about bundles list

composer.json
=> Add Symfony DI component ^4.1 as a conflicting dependency

composer.json
BC breaks?      | no
| Related tickets | fixes #123
=> [Composer] Conflict Symfony 4.1.0

README.md
=> [README] Change Symfony2 to Symfony

README.md
Most of these emails are not active anyway, pointing to our profiles should be a better solution
=> [README] Change authors links

LICENSE, README.md, composer.json, phpunit.xml.dist, src/ApiTestCase.php, src/JsonApiTestCase.php, src/MatcherFactory.php, src/PathBuilder.php, src/XmlApiTestCase.php, test/app/AppKernel.php, test/app/config/doctrine/Category.orm.yml, test/app/config/doctrine/Product.orm.yml, test/app/config/routing.yml, test/app/console, test/src/Controller/SampleController.php, test/src/Entity/Category.php, test/src/Entity/Product.php, test/src/Service/ThirdPartyApiClient.php, test/src/Tests/Controller/SampleControllerJsonTest.php, test/src/Tests/Controller/SampleControllerXmlTest.php, test/src/Tests/DataFixtures/ORM/category.yml, test/src/Tests/DataFixtures/ORM/product.yml
=> Changing namespaces to reflect transfer

README.md
=> [README] Add Lakion credentials

src/ApiTestCase.php, src/JsonApiTestCase.php, src/PathBuilder.php, src/XmlApiTestCase.php, test/app/AppKernel.php, test/src/Controller/SampleController.php, test/src/Entity/Category.php, test/src/Entity/Product.php, test/src/Service/ThirdPartyApiClient.php, test/src/Tests/Controller/SampleControllerJsonTest.php, test/src/Tests/Controller/SampleControllerXmlTest.php
Authors can be found in contributors list anyway.
=> Remove authors doc block in classes

README.md
=> [README] Proper contribution credits

.gitignore, .travis.yml, composer.json, src/ApiTestCase.php, src/Symfony/KernelTestCase.php, src/Symfony/WebTestCase.php, test/src/Tests/Controller/SampleControllerJsonTest.php, test/src/Tests/Controller/SampleControllerXmlTest.php
=> Add support for PHPUnit 8

UPGRADE.md
=> [UPGRADE] Describe v3 to v4 upgrade

composer.json
=> [Composer] After release changes

composer.json, phpstan.neon, src/ApiTestCase.php, src/JsonApiTestCase.php, src/Symfony/KernelTestCase.php, src/Symfony/WebTestCase.php, src/XmlApiTestCase.php
| Related tickets | fixes #106 
Fixing phpstan errors.
=> Fixing phpstan issues

UPGRADE.md, phpunit.xml.dist, src/ApiTestCase.php
| BC breaks?      | yes
| Related tickets | Replaces #154
=> Removing deprecation in the root dir

phpunit.xml.dist
=> [Maintenance] Fix phpunit verbosity

src/ApiTestCase.php
| Related tickets | fixes #153
=> Fix wrong typehint in constructor

.travis.yml, composer.json, easy-coding-standard.yml, src/ApiTestCase.php, src/JsonApiTestCase.php, src/MatcherFactory.php, src/PathBuilder.php, src/Symfony/KernelTestCase.php, src/Symfony/WebTestCase.php, src/XmlApiTestCase.php, test/src/Controller/SampleController.php, test/src/Entity/Category.php, test/src/Entity/Product.php, test/src/Service/ThirdPartyApiClient.php, test/src/Tests/Controller/SampleControllerJsonTest.php, test/src/Tests/Controller/SampleControllerXmlTest.php
=> [Maintenance] Fix CS

.travis.yml, composer.json
=> [Maintenance] Bump php version

.travis.yml, composer.json, easy-coding-standard.yml, phpunit.xml.dist, src/ApiTestCase.php, src/Symfony/WebTestCase.php, src/XmlApiTestCase.php, test/app/AppKernel.php, test/src/Controller/SampleController.php
Copied from https://github.com/lchrusciel/ApiTestCase/pull/163 cause I'm trying to fix it.
=> Symfony 5 support

.travis.yml, composer.json, easy-coding-standard.yml, src/ApiTestCase.php, src/XmlApiTestCase.php
| New feature?    | yes?
#SymfonyHackday
=> Added Symfony 5 support

UPGRADE.md
=> [README] Add upgrade note

.travis.yml, composer.json
=> [Maintenance] Support for PHPUnit 9

.github/workflows/build.yml, composer.json, test/app/AppKernel.php
=> Add support for Symfony 6

.github/workflows/build.yml
=> [Maintenance] Add PHP 8.1 build

.github/workflows/build.yml, composer.json, phpstan.neon, src/ApiTestCase.php, test/src/Controller/SampleController.php
| New feature?    | yes
| Related tickets | N/A
=> Add support for PHPUnit 10

src/ApiTestCase.php, test/src/Tests/Controller/SampleControllerJsonTest.php
| Related tickets | fixes #190
=> [BC] Bring back support for data providers for PHPUnit 9

.github/workflows/build.yml
=> [Maintenance] Support for PHP 8.3

composer.json
=> [Maintenance] Drop Symfony 4 conflict

.github/workflows/build.yml
=> [Maintenance] Remove unneeded excludes in build

.github/workflows/build.yml, composer.json
=> [Maintenance] Update Symfony support

.github/workflows/build.yml
=> [Maintenance] Change github action version

.github/workflows/build.yml, composer.json
=> [Maintenance] Support for PHPUnit 11
